version: "3.8"

services:
  server:
    image: nginx:stable-alpine
    container_name: instaapp_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ./docker/php
    container_name: instaapp_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"

  db:
    image: mysql:8.0
    container_name: instaapp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: instaapp
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
